name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u xivk --password-stdin

    - name: Publish
      run: dotnet publish -c release
      working-directory: ./src/hotdataservice/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xivk/hot-dataservice:latest --tag anywaysopen/edit-api:0.$GITHUB_RUN_NUMBER
      working-directory: ./src/hotdataservice/ 

    - name: Publish the image.
      run: docker push xivk/hot-dataservice:latest
    - name: Publish the image versioned.
      run: docker push anywaysopen/edit-api:0.$GITHUB_RUN_NUMBER
